module.exports = (table) ->
  table.increments()
  table.string('email').unique()
  table.string('downcase').unique()
  table.string('username')
  table.string('password')
  # table.string('remember_token').index()
  # table.string('authentication_token').index()
  table.string('locale', 100).defaultTo('zh')
  table.boolean('actived').defaultTo(false)
  table.boolean('blocked').defaultTo(false)
  table.boolean('superred').defaultTo(false)
  table.integer('followers').defaultTo(0)
  table.integer('following').defaultTo(0)
  table.integer('likes_count').defaultTo(0)
  table.integer('events_count').defaultTo(0)
  table.integer('topics_count').defaultTo(0)
  table.integer('replies_count').defaultTo(0)
  # table.integer('notification_level').defaultTo(0)
  table.integer('external_user_id').defaultTo(0)
  table.integer('failed_attempts').defaultTo(0)
  table.integer('sign_in_count').defaultTo(1)
  # table.timestamp('remember_created_at')
  table.timestamp('current_sign_in_at')
  table.timestamp('last_sign_in_at')
  table.timestamp('blocked_at')
  table.string('bio')
  table.string('blog')
  table.string('provider')
  # table.string('location')
  # table.string('nickname')
  table.string('avatar_url')
  table.string('website_url')
  table.string('last_sign_in_ip')
  table.string('current_sign_in_ip')
  table.timestamps()
